name: タスクテンプレート
about: タスク登録用のテンプレート
title: "[タスク] "
labels:
  - task
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 説明
        タスクの詳細を記入してください。

  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      options:
        - 高
        - 中
        - 低

  - type: input
    id: assignee
    attributes:
      label: 担当者
      description: GitHub のユーザー名

  - type: textarea
    id: status
    attributes:
      label: 現在の状況
      description: 現時点での進捗などを書いてください
